Cleanup service.kill calls in functional tests
The start_service method in the base test class uses the
ServiceFixture which has a cleanup callback to call service.kill.

Any tests that are calling service.kill are redundant calls and
actually result in NoneType error in the compute manager, so
this change removes those redundant cleanups.

Example error trace:

2016-02-24 11:50:26,745 ERROR [nova.service] \
    Service error occurred during cleanup_host
    Traceback (most recent call last):
      File "nova/service.py", line 301, in stop
        self.manager.cleanup_host()
      File "nova/compute/manager.py", line 1329, in cleanup_host
        self.instance_events.cancel_all_events()
      File "nova/compute/manager.py", line 586, in cancel_all_events
        for instance_uuid, events in our_events.items():
    AttributeError: 'NoneType' object has no attribute 'items'

Partial-Bug: #1549401

Change-Id: Ied547985171ced2d9cd524a70dc72d524e7c4f51