Fix is_image_extendable() thinko
In change I34e2f29e1f068636036226a7745d88640f724d93 (virt: convert disk API
over to use nova.virt.image.model) is_image_extendable() causes instances to
fail to boot with:

Traceback (most recent call last):
<snip>
  File "/opt/stack/nova/nova/virt/disk/api.py", line 272, in is_image_extendable
    utils.execute('e2label', image.file)
AttributeError: 'LocalFileImage' object has no attribute 'file'

Use image.path instead

Change-Id: Ia7c3375dc962b369f82c6a5ffb438a4b74330cd9