Fix conductor processes race trying to join servicegroup (zk driver)
When conductor is run in multi process manner and zk (zookeeper) driver
is used as servicegroup driver, there is a problem because each process
tries to manage own Membership object to the same zookeeper path.

This ends with raising exceptions:

RuntimeError: Duplicated membership name /servicegroups/conductor/MEMBER_ID

Zookeeper driver uses Membership (evzookeeper) class with path related
to service type and AFAIK it isn't correct that many process will be
responsible for the same ephemeral node. From my research it is not
supported but evzookeeper (Membership class) - so we can ignore the
exception or give each process his own node.

If we ignore exception (silent it) and when first registered process dies
and the ephemeral node disappears, another process will create it. It will
work but hides the information about overall structure of services and
also causes that each process endlessly will be trying to create a node
(sending invalid create node requests to zookeeper). IMO is not a clean solution.

So there is another solution that each process has its own node. This
fix does that.

The best unique identifier for process is pid, so the chosen solution,
reorganizes the structure of zookeeper tree by adding one more level
with process ids.

The zookeeper tree before looks like this:

/servicesgroups/SERVICE/MEMBER

and after path will look like this:

/servicegroups/SERVICE/MEMBER/PID
eg.
/servicegroups/conductor/foo/12345

This solution also assumes, that servicegroup driver will not check existence of
member node, but existence of subnodes (pids) - which corresponds to existence
of processes of given service.

In general we will have more granular information about whole system -
for exmaple we can check number of processes of given service on each node.

To answer the question: is service on given node works, we have to check
number of ephemeral "pids" nodes in get_all() method.

Closes-bug: #1390511

Related-bug: #1389782
Related-bug: #1382153

Change-Id: I478845b6921dcfb9e9af5a45283a8569051b4f4f