Fixes volume attach issue on Hyper-V
Fixes Bug: #1074717

During volume attach on Windows a process is spawned. The process
currently fails with the following exception, due to eventlet monkey
patching of the os module.

NotImplementedError: set_nonblocking() on a file object with no
setblocking() method (Windows pipes don't support non-blocking I/O)

The fix consists in avoiding monkey patching the os module in
nova-compute on Hyper-V

Change-Id: Ib513bc218da83b751439bad114baac24b08e3d02