Create name_label local variable for logging message
The missing local variable will end up logging an exception instead of
the intended message, however the code will continue functioning fine.

Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/__init__.py", line 776, in emit
    msg = self.format(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 654, in format
    return fmt.format(record)
  File "/home/johannes/openstack/nova/trunk/nova/log.py", line 257, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 436, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
KeyError: u'name_label'

Change-Id: I80bd91a8df51d5411e63ba6a44f227251baf2ab2