Fix api samples image service stub
If you enable CastAsCall with test_api_samples, test_post_backup_server
fails because the ImageService.detail() method returns None and you
get:

  TypeError: object of type 'NoneType' has no len()

Fix by returning an empty list.

blueprint: oslo-messaging
Change-Id: I0cc413d6d428caebb1f67cbc701a36227dead567