Make FaultWrapper handle exception code = None.
Updates the FaultWrapper middleware so that it properly handles
exceptions which contain a code variable set to None. Previously
you'd get TypeError exception like this in the api.log file:

 TypeError: %d format: a number is required, not NoneType

This was due to the fact that we tried to format a string with
an integer value which was set to None.

I hit this today when using Qpid which does in fact throw exceptions
which contain 'code' variables set to None.

Fixes LP Bug #1035159.

Change-Id: I7193031b1f5f9bf84cdb476f8f1268efc50eadf0