Fix a TypeError that occurs in _reschedule.
Updates the compute manager so that it passes the correct
arguments to the scheduler API's run_instance function.

Fixes the following exception which will occur if an instance
is rescheduled:

  TypeError: run_instance() got an unexpected keyword argument
  'reservations'

As part the fix the FakeSchedulerAPI we use in test_compute.py
has been updated to match the arguments of the real scheduler API.

Fixes LP Bug #1038193.

Change-Id: I25782b79a7b19013b25cb94cc5569b5aa83a2df0